repos:
  - repo: local
    hooks:
      - id: vaulttool-encrypt
        name: VaultTool Encrypt
        entry: bash -c 'if [ -f .vaulttool.yml ]; then poetry run vaulttool encrypt; else echo "Skipping VaultTool encrypt - no .vaulttool.yml found"; fi'
        language: system
        pass_filenames: false
        always_run: true
      - id: vaulttool-check-ignore
        name: VaultTool Check Ignore
        entry: bash -c 'if [ -f .vaulttool.yml ]; then poetry run vaulttool check-ignore; else echo "Skipping VaultTool check-ignore - no .vaulttool.yml found"; fi'
        language: system
        pass_filenames: false
      - id: pytest
        name: Pytest
        entry: bash -lc "VAULTTOOL_PRECOMMIT=1 poetry run python3 -B -m pytest -q -o cache_dir=.git/.pytest_cache"
        language: system
        pass_filenames: false

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.5
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
        types: [python]
