repos:
  - repo: local
    hooks:
      - id: vaulttool-encrypt
        name: VaultTool Encrypt
        entry: poetry run vaulttool encrypt
        language: system
        pass_filenames: false
        always_run: true
      - id: vaulttool-check-ignore
        name: VaultTool Check Ignore
        entry: poetry run vaulttool check-ignore
        language: system
        pass_filenames: false
      - id: pytest
        name: Pytest
        entry: bash -lc "VAULTTOOL_PRECOMMIT=1 poetry run python3 -B -m pytest -q -o cache_dir=.git/.pytest_cache"
        language: system
        pass_filenames: false

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.5
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
        types: [python]
