---
# Local VaultTool configuration

vaulttool:
  include_directories:
    - "." # Current directory

  # Directories to exclude from vaulting.
  exclude_directories:
    - ".venv"
    - ".git"
    - "__pycache__"

  include_patterns:
    - "*.env"
    - "*.ini"
    - "*.json"

  exclude_patterns:
    - "*.log"
    - "*example*"
    - "*.vault"

  options:
    suffix: ".vault"
    algorithm: "aes-256-cbc"
    key_type: "file"
    key_file: "/home/josef/.vaulttool/vault.key"
    openssl_path: "openssl"
