blank_issues_enabled: false
contact_links:
  - name: Documentation
    url: https://github.com/jifox/vaulttool/blob/main/README.md
    about: Check out our comprehensive README and documentation
  - name: Discussions
    url: https://github.com/jifox/vaulttool/discussions
    about: Ask questions and discuss ideas with the community
  - name: Security Vulnerabilities
    url: https://github.com/jifox/vaulttool/security/advisories/new
    about: Report security vulnerabilities privately
