name: pre-commit

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    container:
      image: python:3.12-slim
    env:
      PIP_DISABLE_PIP_VERSION_CHECK: "1"
      PYTHONUNBUFFERED: "1"
      VAULTTOOL_PRECOMMIT: "1"
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install system dependencies
        run: |
          apt-get update
          apt-get install -y --no-install-recommends git
          rm -rf /var/lib/apt/lists/*

      - name: Install dependencies
        run: |
          python -m pip install pre-commit pytest
          python -m pip install -r requirements.txt

      - name: Run pre-commit
        uses: pre-commit/action@v3.0.1
        with:
          extra_args: --all-files
